include:
  - template: Auto-DevOps.gitlab-ci.yml

services:
  - postgres

variables:
  POSTGRES_ENABLED: "true"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: v2land

doc_pages:
  needs: []
  image: node:alpine
  stage: deploy
  cache:
    untracked: true
    paths:
      - node_modules
  script:
    - yarn install
    - yarn run compodoc -p tsconfig.json -d public
  artifacts:
    paths:
      - public
