include:
  - template: Auto-DevOps.gitlab-ci.yml

doc_pages:
  needs: []
  image: node:alpine
  stage: deploy
  cache:
    untracked: true
    paths:
      - node_modules
  script:
    - yarn install
    - yarn run compodoc -p tsconfig.json -d public
  artifacts:
    paths:
      - public
